# Alertmanager Configuration for Crypto Trading MVP
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@crypto-trading-mvp.com'

# Route configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 5s
      repeat_interval: 30m

# Receivers configuration
receivers:
  - name: 'default-receiver'
    webhook_configs:
      - url: 'http://api:8000/api/system/alerts'
        send_resolved: true

  - name: 'critical-alerts'
    webhook_configs:
      - url: 'http://api:8000/api/system/alerts/critical'
        send_resolved: true
