name: Security Checks - Bot Trading MVP

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  dependency-check:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install security tools
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit

      - name: Safety
        run: |
          safety check --full-report | tee safety-report.txt || true

      - name: Bandit
        run: |
          bandit -r . -q | tee bandit-report.txt || true

      - name: Upload text reports
        uses: actions/upload-artifact@v4
        with:
          name: security-logs
          path: |
            safety-report.txt
            bandit-report.txt

  security-report:
    name: Security Report (Summary)
    runs-on: ubuntu-latest
    needs: [ dependency-check ]
    if: always()
    steps:
      - name: Create summary file
        shell: bash
        run: |
          {
            echo "# Security Report - $(date)"
            echo
            echo "## Job Status"
            echo "- Dependency Check: ${{ needs.dependency-check.result }}"
            echo
            echo "## Notes"
            echo "- Safety and Bandit ran. Check job logs for details."
          } > security-summary.md
          cat security-summary.md

      - name: Upload summary
        uses: actions/upload-artifact@v4
        with:
          name: security-summary
          path: security-summary.md
