name: Security Checks - Bot Trading MVP

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'

# Permissões mínimas p/ subir SARIF e ler conteúdo
permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  # Job 1: Análise de Dependências
  dependency-check:
    name: 🔒 Dependency Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Print Python & pip (debug)
        run: |
          python -V
          pip -V

      - name: Instalar ferramentas de segurança
        run: |
          python -m pip install --upgrade pip
          pip install safety bandit

      - name: Verificar vulnerabilidades conhecidas (Safety)
        run: |
          safety check --json --output safety-report.json || true

      - name: Análise de código com Bandit
        run: |
          bandit -r . -f json -o bandit-report.json || true

      # Semgrep via action oficial (mais estável do que pip)
      - name: Semgrep SAST
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          generateSarif: true
          sarifFile: semgrep-report.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload relatórios de segurança
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            safety-report.json
            bandit-report.json
            semgrep-report.sarif

  # Job 2: Análise de Secrets
  secret-scan:
    name: 🔐 Secret Detection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Executar GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
        # with:
        #   args: "--verbose"  # opcional

  # Job 3: Análise de Container
  container-security:
    name: 🐳 Container Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build imagem Docker
        run: |
          docker build -t trading-bot:security-scan .

      - name: Executar Trivy (vulnerabilidades)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'trading-bot:security-scan'
          format: 'sarif'
          output: 'trivy-results.sarif'
          ignore-unfixed: true

      - name: Executar Trivy (configuração)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'config'
          format: 'sarif'
          output: 'trivy-config-results.sarif'

      - name: Upload resultados do Trivy para GitHub Security
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: |
            trivy-results.sarif
            trivy-config-results.sarif

  # Job 4: Análise de Código Estática (CodeQL)
  codeql-analysis:
    name: 🔍 CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python', 'javascript' ]

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Inicializar CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Executar análise CodeQL
        uses: github/codeql-action/analyze@v3

  # Job 5: Verificação de Licenças
  license-check:
    name: 📄 License Compliance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar pip-licenses
        run: |
          python -m pip install --upgrade pip
          pip install pip-licenses

      - name: Verificar licenças das dependências
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
            pip-licenses --format=json --output-file=licenses-report.json
            pip-licenses --format=plain-vertical
          fi

      - name: Verificar licenças problemáticas
        run: |
          python - <<'PY'
import json, sys, os
forbidden = {'GPL-3.0','AGPL-3.0','LGPL-3.0'}
if os.path.exists('licenses-report.json'):
    with open('licenses-report.json','r') as f:
        licenses = json.load(f)
    issues = [f"{p['Name']} ({p['License']})" for p in licenses if p.get('License') in forbidden]
    if issues:
        print('❌ Licenças problemáticas encontradas:')
        for i in issues: print('  -', i)
        sys.exit(1)
    else:
        print('✅ Todas as licenças são compatíveis')
PY

      - name: Upload relatório de licenças
        uses: actions/upload-artifact@v4
        with:
          name: license-report
          path: licenses-report.json

  # Job 6: Verificação de Configuração
  config-security:
    name: ⚙️ Configuration Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Verificar arquivos de configuração sensíveis
        run: |
          echo "🔍 Verificando configurações de segurança..."
          SENSITIVE_FILES=".env .env.local .env.production config.ini secrets.json"
          for file in $SENSITIVE_FILES; do
            if [ -f "$file" ]; then
              echo "⚠️  Arquivo sensível encontrado: $file"
              head -5 "$file" || true
            fi
          done
          if [ -f "Dockerfile" ]; then
            echo "🐳 Verificando Dockerfile..."
            grep -q "USER root" Dockerfile && echo "⚠️  Dockerfile executa como root" || true
            grep -q "ADD http" Dockerfile && echo "⚠️  Dockerfile usa ADD com HTTP (inseguro)" || true
            grep -q "RUN.*sudo" Dockerfile && echo "⚠️  Dockerfile usa sudo" || true
          fi
          if [ -f "docker-compose.yml" ]; then
            echo "🐳 Verificando docker-compose.yml..."
            grep -q "privileged: true" docker-compose.yml && echo "⚠️  Container com privilégios elevados" || true
            grep -q "network_mode.*host" docker-compose.yml && echo "⚠️  Container usando network host" || true
          fi

  # Job 7: Relatório Consolidado
  security-report:
    name: 📊 Security Report
    runs-on: ubuntu-latest
    needs: [dependency-check, secret-scan, container-security, license-check, config-security]
    if: always()

    steps:
      - name: Download todos os artefatos
        uses: actions/download-artifact@v4

      - name: Gerar relatório consolidado
        run: |
          echo "# 🔒 Relatório de Segurança - $(date)" > security-summary.md
          echo "" >> security-summary.md
          echo "## 📊 Status dos Jobs" >> security-summary.md
          echo "- Dependency Check: ${{ needs.dependency-check.result }}" >> security-summary.md
          echo "- Secret Scan: ${{ needs.secret-scan.result }}" >> security-summary.md
          echo "- Container Security: ${{ needs.container-security.result }}" >> security-summary.md
          echo "- License Check: ${{ needs.license-check.result }}" >> security-summary.md
          echo "- Config Security: ${{ needs.config-security.result }}" >> security-summary.md
          echo "" >> security-summary.md
          if [ -d "security-reports" ]; then
            echo "## 🔍 Vulnerabilidades Encontradas" >> security-summary.md
            if [ -f "security-reports/safety-report.json" ]; then
              python - <<'PY' >> security-summary.md
import json, sys
try:
    data = json.load(open('security-reports/safety-report.json'))
    if data:
        print(f"- {len(data)} vulnerabilidades encontradas")
        for vuln in data[:5]:
            print(f"  - {vuln.get('advisory','N/A')}")
    else:
        print("- Nenhuma vulnerabilidade encontrada")
except Exception as e:
    print(f"- Erro ao processar relatório: {e}")
PY
            fi
          fi
          echo "" >> security-summary.md
          echo "## 🎯 Recomendações" >> security-summary.md
          echo "1. Revisar e corrigir vulnerabilidades de alta severidade" >> security-summary.md
          echo "2. Atualizar dependências com vulnerabilidades conhecidas" >> security-summary.md
          echo "3. Implementar rotação regular de secrets" >> security-summary.md
          echo "4. Configurar alertas de segurança automáticos" >> security-summary.md
          cat security-summary.md

      - name: Upload relatório consolidado
        uses: actions/upload-artifact@v4
        with:
          name: security-summary
          path: security-summary.md

      - name: Comentar no PR (se aplicável)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const summary = fs.readFileSync('security-summary.md', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: summary
            });
